language: node_js
node_js:
  - '14.17.0'

cache:
  npm: true
  directories:
    - '~/.pnpm-store'
before_install:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
script:
  - pnpm coverage && coveralls < coverage/lcov.info
branches:
  only: main
