language: node_js
node_js:
  - '14.17.0'

cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn coverage && coveralls < coverage/lcov.info
branches:
  only: main
